create table category (category_id uuid not null, category_desc varchar(255), category_name varchar(255), primary key (category_id));
create table order (order_id uuid not null, amount int4 not null, price float4 not null, primary key (order_id));
create table order_products (order_order_id uuid not null, products_product_id uuid not null);
create table product (product_id uuid not null, date_create timestamp, date_sale timestamp, date_update timestamp, product_amount int4 not null, product_cost float4 not null, product_desc varchar(255), product_image varchar(255), product_name varchar(255), product_rating int4 not null, product_sale int4 not null, categories_category_id uuid, primary key (product_id));
create table user (user_id uuid not null, user_active boolean default false, user_address varchar(255), user_country varchar(255), user_email varchar(255), user_image varchar(255), user_name varchar(255), user_password varchar(255), user_phone varchar(255), user_role varchar(255), orders_order_id uuid, primary key (user_id));
alter table if exists user add constraint UKk5ybf30ooo0e649gc1rn27qc unique (user_id, user_name, user_email);
alter table if exists order_products add constraint FK16ex68h7pvahxh1ft6updos1c foreign key (products_product_id) references product;
alter table if exists order_products add constraint FKg72n53f6uwco1i8rod765gkoi foreign key (order_order_id) references order;
alter table if exists product add constraint FK83kimldx4nmma01p8w9ql5u54 foreign key (categories_category_id) references category;
alter table if exists user add constraint FKs5y132po7bs1awsm9ifq1pyjl foreign key (orders_order_id) references order;
