create table category (categoryid uuid not null, category_desc varchar(255), category_name varchar(255), primary key (categoryid));
create table order (orderid uuid not null, amount int4 not null, price float4 not null, primary key (orderid));
create table order_products (order_orderid uuid not null, products_productid uuid not null);
create table product (productid uuid not null, date_create timestamp, date_sale timestamp, date_update timestamp, product_amount int4 not null, product_cost float4 not null, product_desc varchar(255), product_image varchar(255), product_name varchar(255), product_rating int4 not null, product_sale int4 not null, categories_categoryid uuid, primary key (productid));
create table user (userid uuid not null, user_active boolean default false, user_address varchar(255), user_country varchar(255), user_email varchar(255), user_image varchar(255), user_name varchar(255), user_password varchar(255), user_phone varchar(255), user_role varchar(255), orders_orderid uuid, primary key (userid));
alter table if exists user add constraint UKej08kn21pn7nj4rv903cav32v unique (userid, user_name, user_email);
alter table if exists order_products add constraint FKadfqt91ykc705u2ctcptodbnt foreign key (products_productid) references product;
alter table if exists order_products add constraint FKqnh6h0334u0a1j15ni8rpgy1k foreign key (order_orderid) references order;
alter table if exists product add constraint FKlv17y78d4ie52nnt48yofye0r foreign key (categories_categoryid) references category;
alter table if exists user add constraint FKb36c0tni63ya2ifc8buh1dasg foreign key (orders_orderid) references order;
create table category (categoryid uuid not null, category_desc varchar(255), category_name varchar(255), primary key (categoryid));
create table order (orderid uuid not null, amount int4 not null, price float4 not null, primary key (orderid));
create table order_products (order_orderid uuid not null, products_productid uuid not null);
create table product (productid uuid not null, date_create timestamp, date_sale timestamp, date_update timestamp, product_amount int4 not null, product_cost float4 not null, product_desc varchar(255), product_image varchar(255), product_name varchar(255), product_rating int4 not null, product_sale int4 not null, categories_categoryid uuid, primary key (productid));
create table user (userid uuid not null, user_active boolean default false, user_address varchar(255), user_country varchar(255), user_email varchar(255), user_image varchar(255), user_name varchar(255), user_password varchar(255), user_phone varchar(255), user_role varchar(255), orders_orderid uuid, primary key (userid));
alter table if exists user add constraint UKej08kn21pn7nj4rv903cav32v unique (userid, user_name, user_email);
alter table if exists order_products add constraint FKadfqt91ykc705u2ctcptodbnt foreign key (products_productid) references product;
alter table if exists order_products add constraint FKqnh6h0334u0a1j15ni8rpgy1k foreign key (order_orderid) references order;
alter table if exists product add constraint FKlv17y78d4ie52nnt48yofye0r foreign key (categories_categoryid) references category;
alter table if exists user add constraint FKb36c0tni63ya2ifc8buh1dasg foreign key (orders_orderid) references order;
create table category (categoryid uuid not null, category_desc varchar(255), category_name varchar(255), primary key (categoryid));
create table order (orderid uuid not null, amount int4 not null, price float4 not null, primary key (orderid));
create table order_products (order_orderid uuid not null, products_productid uuid not null);
create table product (productid uuid not null, date_create timestamp, date_sale timestamp, date_update timestamp, product_amount int4 not null, product_cost float4 not null, product_desc varchar(255), product_image varchar(255), product_name varchar(255), product_rating int4 not null, product_sale int4 not null, categories_categoryid uuid, primary key (productid));
create table user (userid uuid not null, user_active boolean default false, user_address varchar(255), user_country varchar(255), user_email varchar(255), user_image varchar(255), user_name varchar(255), user_password varchar(255), user_phone varchar(255), user_role varchar(255), orders_orderid uuid, primary key (userid));
alter table if exists user add constraint UKej08kn21pn7nj4rv903cav32v unique (userid, user_name, user_email);
alter table if exists order_products add constraint FKadfqt91ykc705u2ctcptodbnt foreign key (products_productid) references product;
alter table if exists order_products add constraint FKqnh6h0334u0a1j15ni8rpgy1k foreign key (order_orderid) references order;
alter table if exists product add constraint FKlv17y78d4ie52nnt48yofye0r foreign key (categories_categoryid) references category;
alter table if exists user add constraint FKb36c0tni63ya2ifc8buh1dasg foreign key (orders_orderid) references order;
